export const Add_Ing="Add"
export const remove_Ing="Remove"
export const OnInitPurchase="Purchase"
export const Purchasesuccess="Purchasesuccess"
export const PurchaseStart="PurchaseStart"
export const LoadBurger="LoadIngs"
export const newPurchase="newPurchase"
export const error="Error"
export const FetchOrder="OrderArray"
export const OnAuth="Authentication"
export const Auth_Start="AuthStart"
export const Auth_Succ="AuthSucces"
export const AuthLogOut="Logout"
export const Auth_Fail="AuthFail"
export const SET_PATH="RedirectPath"
export const LD_APP_BE_AUTH="LoaDCO"
export const CH_ING="IngreStatus"
export const onRedirect ="onRedirect"
export const Reload="Reload"
export const Login="Login"
export const Fetch_Start="Fetch_Start"
export const Fetch_Succ="Fetch_Succ"
export const Fetch_Fail="Fetch_Fail"
export const FetchChat_Succes="FetchChat_Succes"
export const FetchChat_Fail="FetchChat_Fail"
export const chat_CleanUp="chat_CleanUp"
export const AddToChatArray="AddToChatArray"
export const Status="Status"
export const setStaus="setStaus"

export const GetUser="GetUser"
export const FetchUserChat="FetchUserChat"
export const ChatLoader="ChatLoader"
export const setSocket="setSocket"

export const FetchArray="FetchArray"

export const newSingUp="newSingUp"

export const UpdateChatBox="UpdateChatBox"
export const boxupdateStarted="boxupdateStarted"